# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 19:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cliente', '0002_auto_20170801_1355'),
        ('outros', '0020_auto_20170807_1558'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=datetime.datetime(2017, 8, 7, 15, 58, 11, 226692))),
                ('confirmado', models.CharField(choices=[('S', 'Sim'), ('N', 'Nao')], max_length=1)),
                ('cliente1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente')),
                ('func1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.funcionario')),
                ('servico1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.servico')),
            ],
        ),
    ]
