# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170801_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='telefone2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
