# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170801_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 17, 57, 6, 692569)),
        ),
    ]
