# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 19:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20170808_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 15, 37, 59, 714965)),
        ),
    ]
