# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 21:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20170812_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 17, 34, 38, 32596)),
        ),
    ]
