# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0033_auto_20171024_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 14, 39, 32, 260830)),
        ),
    ]
