# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='funcionario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.IntegerField()),
                ('telefone1', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='servico1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('funcionario2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.funcionario')),
                ('servico2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.servico')),
            ],
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 10, 13, 49, 971613)),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='servicos',
            field=models.ManyToManyField(to='outros.servico1'),
        ),
    ]
