# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 21:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0005_auto_20170801_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('qnt', models.IntegerField()),
                ('obs', models.CharField(blank=True, max_length=200, null=True)),
                ('produto1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='outros.produto')),
            ],
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 1, 17, 13, 46, 319845)),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='produtos',
            field=models.ManyToManyField(to='outros.item'),
        ),
    ]
