# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-05 13:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0013_auto_20170804_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='func',
            field=models.CharField(choices=[('C', 'Cabelereiro'), ('R', 'Recepcionista')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 5, 9, 41, 7, 723134)),
        ),
    ]
