# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 17:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cliente', '0002_auto_20170801_1355'),
        ('outros', '0015_auto_20170805_0945'),
    ]

    operations = [
        migrations.AddField(
            model_name='comanda',
            name='cliente1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cliente.cliente'),
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 13, 57, 31, 866018)),
        ),
    ]
