# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0017_auto_20170807_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='comanda_corte',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.DateTimeField(default=datetime.datetime(2017, 8, 7, 14, 4, 10, 386500))),
                ('total', models.DecimalField(decimal_places=2, max_digits=5)),
                ('servicos', models.ManyToManyField(to='outros.servico1')),
            ],
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 7, 14, 4, 10, 385500)),
        ),
    ]
