# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0023_auto_20170808_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 16, 52, 43, 132486)),
        ),
        migrations.AlterField(
            model_name='comanda_corte',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 16, 52, 43, 137494)),
        ),
    ]
