# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-15 15:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0028_auto_20170812_1734'),
        ('outros', '0027_auto_20170814_1151'),
    ]

    operations = [
    ]
