# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0033_auto_20171024_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco',
            new_name='preco_comp',
        ),
        migrations.AddField(
            model_name='produto',
            name='preco_vend',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 14, 39, 32, 248822)),
        ),
        migrations.AlterField(
            model_name='comanda_corte',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 14, 39, 32, 252824)),
        ),
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('P', 'Barbearia'), ('B', 'Bar')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
