# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('outros', '0038_auto_20171107_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='preco_venda',
            new_name='preco_vend',
        ),
        migrations.AlterField(
            model_name='comanda',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 18, 45, 397189)),
        ),
        migrations.AlterField(
            model_name='comanda_corte',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 18, 45, 399339)),
        ),
    ]
