# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 18, 6, 10, 594605)),
        ),
    ]
