# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 22:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0002_caixa_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='desc',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 4, 18, 8, 7, 69887)),
        ),
    ]
