# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-08 20:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0013_auto_20170808_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 8, 16, 52, 43, 146999)),
        ),
        migrations.AlterField(
            model_name='caixa',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
