# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0015_auto_20170813_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 15, 41, 32, 672845, tzinfo=utc)),
        ),
    ]
