# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-12 19:42
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_auto_20170812_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 12, 15, 42, 26, 313876)),
        ),
    ]
