# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-14 15:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0016_auto_20170814_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 8, 14, 15, 51, 22, 583171, tzinfo=utc)),
        ),
    ]
