# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-26 17:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0023_auto_20171024_1711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 26, 17, 39, 32, 256828, tzinfo=utc)),
        ),
    ]
