# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-31 12:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0025_auto_20171030_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 31, 12, 55, 13, 647198, tzinfo=utc)),
        ),
    ]
