# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-07 14:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('caixa', '0027_auto_20171031_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caixa',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2017, 11, 7, 14, 13, 50, 473853, tzinfo=utc)),
        ),
    ]
